#!/usr/bin/env bash
# Display "Best School" 9 times then printing "Hi" on the 10th line

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((index++))
done
