#!/usr/bin/env bash
# Displaying "bad luck on 4th iter
# Displaying "good luck" on 8th iter
# Displaying "Best School" for remaining iters

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"

	elif [ $count -eq 8 ]
	then
		echo "good luck"
	
	else
		echo "Best School"
	fi

	(( index++ ))
done		


