#!/usr/bin/env bash
# Displaying "bad luck on 4th iter
# Displaying "good luck" on 8th iter
# Displaying "Best School" for remaining iters

index=0

while [ $index -lt 10 ]
do
	if [ $index -eq 4 ]
	then
		echo "bad luck"

	elif [ $index -eq 8 ]
	then
		echo "good luck"
	
	else
		echo "Best School"
	fi

	(( index++ ))
done		


